from typing import Any,  Optional, Protocol

from wyzecam.api_models import WyzeCamera
from wyzebridge.wyze_stream_options import WyzeStreamOptions

class Stream(Protocol):
    camera: WyzeCamera
    options: WyzeStreamOptions
    start_time: float
    uri: str

    @property
    def connected(self) -> bool: ...

    @property
    def enabled(self) -> bool: ...

    @property
    def motion(self) -> bool: ...

    def init(self) -> bool: ...

    def start(self) -> bool: ...

    def stop(self) -> bool: ...

    def enable(self) -> bool: ...

    def disable(self) -> bool: ...

    def health_check(self) -> int: ...

    def get_info(self, item: Optional[str] = None) -> dict: ...

    def status(self) -> str: ...

    def send_cmd(self, cmd: str, payload: str | list | dict = "") -> dict: ...
