services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: wyze-bridge # For tailscale
    restart: unless-stopped
    ports:
      - 8554:8554 # RTSP
      - 8889:8889 #WebRTC
      - 8189:8189/udp # WebRTC/ICE
      - 5000:5000 # WEB-UI 
    cap_add: [NET_ADMIN]
    environment:
      - TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      - TS_EXTRA_ARGS=--accept-routes
      - TS_USERSPACE=false
    volumes:
      - /dev/net/tun:/dev/net/tun
  wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:latest
    depends_on: [tailscale]
    network_mode: service:tailscale
    environment:
      # [OPTIONAL] Credentials can be set in the WebUI
      # API Key and ID can be obtained from the wyze dev portal:
      # https://developer-api-console.wyze.com/#/apikey/view
      - WYZE_EMAIL=
      - WYZE_PASSWORD=
      - API_ID=
      - API_KEY=
      # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
      # - WB_IP=192.168.1.122
      # WebUI and Stream authentication:
      - WB_AUTH=True # Set to false to disable web and stream auth.
      # WB_USERNAME=
      # WB_PASSWORD=