FROM multiarch/debian-debootstrap:armhf-bullseye-slim
RUN apt-get update && apt-get install g++ ffmpeg python3 python3-pip python3-numpy python3-av unzip -y && rm -rf /var/lib/apt/lists/*
RUN pip3 install requests wyzecam
ADD https://github.com/nblavoie/wyzecam-api/raw/master/wyzecam-sdk/TUTK_IOTC_Platform_14W42P1.zip /tmp/tutk.zip
RUN unzip /tmp/tutk.zip -d /tmp/tutk/ && cd /tmp/tutk/Lib/Linux/Arm11_BCM2835_4.8.3/ && g++  -fpic -shared -Wl,--whole-archive libAVAPIs.a libIOTCAPIs.a -Wl,--no-whole-archive -o libIOTCAPIs_ALL.so && cp libIOTCAPIs_ALL.so /usr/local/lib/ && rm -rf /tmp/tutk.zip /tmp/tutk/
ADD https://gist.github.com/noelhibbard/03703f551298c6460f2fd0bfdbc328bd/raw/08666ddae0fa18e9b3d29ded9e028906400b10a2/wyzecam-to-rtmp.py /opt/wyzecam/wyzecam-to-rtmp.py
COPY cameras.py /opt/wyzecam/cameras.py
CMD [ "python3", "/opt/wyzecam/cameras.py" ]