FROM arm32v7/python:3.9-slim
RUN apt-get update && apt-get install ffmpeg unzip g++ -y && rm -rf /var/lib/apt/lists/*
RUN pip3 install requests wyzecam 
ADD https://github.com/nblavoie/wyzecam-api/raw/master/wyzecam-sdk/TUTK_IOTC_Platform_14W42P1.zip /tmp/tutk.zip
RUN unzip /tmp/tutk.zip -d /tmp/tutk/ && cd /tmp/tutk/Lib/Linux/Arm11_BCM2835_4.8.3/ && g++  -fpic -shared -Wl,--whole-archive libAVAPIs.a libIOTCAPIs.a -Wl,--no-whole-archive -o libIOTCAPIs_ALL.so && cp libIOTCAPIs_ALL.so /usr/local/lib/ && rm -rf /tmp/tutk.zip /tmp/tutk/
RUN mkdir -p /opt/wyzecam/tokens
COPY cameras.py /opt/wyzecam/cameras.py
CMD [ "python3", "/opt/wyzecam/cameras.py" ]