name: Docker Wyze Bridge (DEV branch)
description: DEV build. Use the REBUILD button to pull latest image.
slug: docker_wyze_bridge_dev
url: "https://github.com/mrlt8/docker-wyze-bridge"
version: dev
stage: experimental
arch:
  - armv7
  - aarch64
  - amd64
startup: application
boot: auto
apparmor: false
hassio_api: true
ports:
  1935/tcp: 1935
  8554/tcp: 8554
  8888/tcp: 8888
  8189/udp: 8189
  8889/tcp: 8889
  5000/tcp: 5000
ports_description:
  1935/tcp: RTMP streams
  8554/tcp: RTSP streams
  8888/tcp: HLS streams
  8189/udp: WebRTC ICE
  8889/tcp: WebRTC streams
  5000/tcp: Web-UI/Snapshots
environment:
  IMG_DIR: media/wyze/img/
  RECORD_PATH: media/wyze/{CAM_NAME}
  MQTT_DTOPIC: homeassistant
map:
  - addon_config:rw
  - media:rw
  - ssl:ro
services:
  - mqtt:want
ingress: true
ingress_port: 5000
panel_icon: mdi:bridge
options:
  ENABLE_AUDIO: true
  ON_DEMAND: true
  WB_AUTH: true
  MOTION_API: true
  MQTT: true
  CAM_OPTIONS: []
schema:
  WYZE_EMAIL: email?
  WYZE_PASSWORD: password?
  API_ID: match(\s*[a-fA-F0-9-]{36}\s*)?
  API_KEY: match(\s*[a-zA-Z0-9]{60}\s*)?
  WB_IP: str?
  REFRESH_TOKEN: str?
  ACCESS_TOKEN: str?
  NET_MODE: list(LAN|P2P|ANY)?
  SNAPSHOT: list(API|RTSP|RTSP15|RTSP30|RTSP60|RTSP180|RTSP300|Disable)?
  SNAPSHOT_FORMAT: str?
  IMG_TYPE: list(jpg|png)?
  IMG_DIR: str?
  ENABLE_AUDIO: bool?
  ON_DEMAND: bool?
  MOTION_API: bool?
  MOTION_INT: float(1.1,)?
  MOTION_START: bool?
  MOTION_WEBHOOKS: str?
  SUBSTREAM: bool?
  AUDIO_CODEC: list(COPY|AAC|LIBOPUS|MP3|PCM_MULAW|PCM_ALAW)?
  AUDIO_FILTER: str?
  LLHLS: bool?
  DISABLE_CONTROL: bool?
  RTSP_FW: bool?
  RECORD_ALL: bool?
  RECORD_LENGTH: int?
  RECORD_PATH: str?
  RECORD_FILE_NAME: str?
  MQTT: bool
  MQTT_HOST: str?
  MQTT_AUTH: str?
  MQTT_TOPIC: str?
  MQTT_DTOPIC: str?
  MQTT_RETRIES: int?
  FILTER_NAMES: str?
  FILTER_MODELS: str?
  FILTER_MACS: str?
  FILTER_BLOCK: bool?
  ROTATE_DOOR: bool?
  H264_ENC: str?
  FORCE_ENCODE: bool?
  IGNORE_OFFLINE: bool?
  OFFLINE_WEBHOOKS: bool?
  FRESH_DATA: bool?
  URI_MAC: bool?
  URI_SEPARATOR: list(-|_|#)?
  QUALITY: str?
  SUB_QUALITY: str?
  FORCE_FPS: int?
  SUB_RECORD: bool?
  FFMPEG_FLAGS: str?
  FFMPEG_CMD: str?
  LOG_LEVEL: list(INFO|DEBUG)?
  LOG_FILE: bool?
  LOG_TIME: bool?
  FFMPEG_LOGLEVEL: list(quiet|panic|fatal|error|warning|info|verbose|debug)?
  IGNORE_RES: int?
  BOA_ENABLED: bool?
  BOA_INTERVAL: int?
  BOA_TAKE_PHOTO: bool?
  BOA_PHOTO: bool?
  BOA_ALARM: bool?
  BOA_MOTION: str?
  BOA_COOLDOWN: int?
  CAM_OPTIONS:
    - CAM_NAME: str?
      AUDIO: bool?
      FFMPEG: str?
      LIVESTREAM: str?
      NET_MODE: str?
      ROTATE: bool?
      QUALITY: str?
      SUB_QUALITY: str?
      FORCE_FPS: int?
      RECORD: bool?
      SUB_RECORD: bool?
      SUBSTREAM: bool?
      MOTION_WEBHOOKS: str?
  MEDIAMTX:
    - match(^\w+=.*)?
  WB_HLS_URL: str?
  WB_RTMP_URL: str?
  WB_RTSP_URL: str?
  WB_WEBRTC_URL: str?
  WB_AUTH: bool?
  WB_USERNAME: str?
  WB_PASSWORD: str?
